### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by vr8hub** [ConcaveTrillion/niccolo-machiavelli_discourses-on-livy_ninian-hill-thomson#2]
- [x] Re the first item on your notes, a cite for a blockquote goes within the blockquote. See SEMoS 5.8.
- [x] The standard I’ve observed from others and used is that we use “part” when there are two levels, “division” and then “part” when there are three. I just checked a few random two-level productions that I didn’t do and confirmed that. The example(s?) in the manual also supports it (see SEMoS 7.1.5.1, e.g.). So, the epub types on the book-X files should be part, not division.
- [x] note-1 has the language tag on the p instead of the blockquote; it should be on the blockquote like the rest.
- [x] The CSS for those should be blockquote[xml|lang], not body[xml|lang]; see SEMoS 8.2.9.6.
- [x] Salutation/valediction are semantics for letters, which the dedication isn’t, so they should be removed and other selectors used to target those paragraphs. Since they’re in the header and the last paragraph, the selectors are pretty straightforward.
- [x] Satires is a book of poems, not a poem itself (like Aenid, e.g.), so its semantic should be book.
- [x] Bellum Catilinae should have a language tag in it’s publication tag.
- [x] The short description should not contain Machaivelli’s name (see SEMoS 9.6.1.2).
- [x] We (when possible) match formatting for verse. So, the first line of the verse in chap. 1-11 should be indented (i4? i6?). And the one in 1-21 (and in that case, the endnote blockquote as well), and so on for the rest.

**Comment by ConcaveTrillion** [comment]
- Regarding the short description, I was copying _The Prince_'s short description and being a little bit tongue-in-cheek. I can change it, but we probably should change _The Prince_ too?

I'll get to work on the rest.

**Comment by vr8hub** [comment]
_The Prince_ is one of SE's oldest works, so it was done long before there was a SEMoS. :) If you want to submit a PR for it, that would be fine.

**Comment by ConcaveTrillion** [comment]
Made all the changes. Also, doing the dedication I realized I missed modernizing the capitalization in that file (I wrote an interactive find/replace python script to help me do it and didn't run it on that file). So that's in the latest commits too.
