### ISSUE TITLE
Re-Review 

### ISSUE THREAD

**Issue by vr8hub** [ConcaveTrillion/niccolo-machiavelli_discourses-on-livy_ninian-hill-thomson#3]
- [x] The new dedication CSS is too broad, so it's making _all_ headers be small-caps, not just the dedication, so all of the bridgeheads are now small-capped italic instead of just italic. It needs a #dedication in front of it.
- [x] I apologize, I did not notice this before. The reference in note-15 is not in a cite, and I believe it therefore needs a period at the end. I'm relative sure but not 100%, so I'll ask Alex when I give it to him.

**Comment by ConcaveTrillion** [comment]
My bad! I totally thought i *did* but #dedication in front of it. thanks. fixing now

**Comment by ConcaveTrillion** [comment]
Fixed these 2 items, I also checked note 11 which is like note 15, and added a period there.
